### ISSUE TITLE
Correção de CORS no express

### ISSUE THREAD

**Issue by WashinRibeiro** [kaualandi/whatsapp-cron#1]
Ao integrar o end-point  de "chats" está dando o seguinte erro de CORS: 
`Access to XMLHttpRequest at 'http://localhost:3007/chats' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by kaualandi** [comment]
Obrigado pela contribuição, @WashinRibeiro, de fato testei apenas no Postman.

Mergeei sua alteração e vou fechar a issue.
